services:
  cluster-master:
    image: firasj/spark-docker-cluster
    container_name: cluster-master
    ports:
      - "8088:8088"
      - "4040:4040"
      - "19888:19888"
      - "9000:9000"
      - "9870:9870"
    volumes:
      - "./app:/app"
    networks:
      - spark-cluster
    depends_on:
      - cluster-slave-1
      - cassandra-server
    hostname: cluster-master
    tty: true
    working_dir: /app
    entrypoint:
      - bash
      - /app/app.sh

  cluster-slave-1:
    image: firasj/spark-docker-cluster
    container_name: cluster-slave-1
    networks:
      - spark-cluster
    hostname: cluster-slave-1
    tty: true

  cassandra-server:
    image: cassandra:5.0
    container_name: cassandra-server
    environment:
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    ports:
      - "9042:9042"
      - "7001:7001"
    networks:
      - spark-cluster
    hostname: cassandra-server
    tty: true

networks:
  spark-cluster:
    driver: bridge